site_name: sem

theme:
  name: "material"

use_directory_urls: false

plugins:
  - mkdocstrings

nav:
  - Homepage: index.md
  - Tutorial:
      - tutorial/schema.md
      - tutorial/basic.md
      - tutorial/adv.md
  - Module reference:
      - reference/Common.md
      - reference/CQTableView.md
      - reference/ListForm.md
      - reference/MainWindow.md
      - reference/ModelWrapper.md
